title: Taiwan News Daily
description: 台灣每日新聞摘要彙整，收錄過去 24 小時內的熱門報導
lang: zh-TW
url: https://lazyjerry.github.io
baseurl: /taiwan-news
remote_theme: jekyll/minima

minima:
  skin: dark
  hide_site_feed_link: true
  nav_pages: []

permalink: pretty

header_pages: []

plugins:
  - jekyll-remote-theme
